#!/usr/bin/env bash
# A while loop to loop from 1 to 20, while displaying custom messages on 4, 9, and 17
i=1
while [ "$i" -lt 21 ]; do
    echo "$i"
    case "$i" in 
        4)
           echo "bad luck from China"
           ;;
        9)
            echo "bad luck from Japan"
           ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo ""
            ;;
        esac
        
    ((i++))
done 
